site_name: NMCPYe Data Mapping
site_url: https://hamza-ye.github.io/nmcpye-data-mapping/
site_author: NMCP Yemen
repo_name: Hamza-ye/nmcpye-data-mapping
repo_url: https://github.com/Hamza-ye/nmcpye-data-mapping
edit_uri: edit/master/documentation/docs/

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    # - content.action.view
    - content.code.annotate
    # - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      # enable_creation_date: true
      type: timeago
  # - git-committers:
  #     enabled: !ENV [CI, false]
  #     repository: Hamza-ye/nmcpye-data-mapping
  #     branch: master
  - git-authors

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Hamza-ye

markdown_extensions:
  - tables
  - def_list
  - md_in_html
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
        # nav:
        #   - Home: index.md
        #   - Data Files: data-files.md
        #   - About: about.md


extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

copyright: |
  &copy; 2023 <a href="https://github.com/Hamza-ye/nmcpye-data-mapping"  target="_blank" rel="noopener">NMCP Yemen</a>
